///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class GetUserMessagesResponseData {
/*
{
  "id": "1",
  "from_user_id": "3",
  "to_user_id": "4",
  "message": "test",
  "attachment": null,
  "date_time": "2023-08-08 10:15:54",
  "image_url": "uploads/speakers/3/headshot/e050c30de041aa6c97fdc35c6af270cf.jpg"
}
*/

  String? id;
  String? fromUserId;
  String? toUserId;
  String? message;
  String? attachment;
  String? dateTime;
  String? imageUrl;
  String? tempId;
  // String? imageSync;

  GetUserMessagesResponseData({
    this.id,
    this.fromUserId,
    this.toUserId,
    this.message,
    this.attachment,
    this.dateTime,
    this.imageUrl,
    this.tempId,
    // this.imageSync,
  });
  GetUserMessagesResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    fromUserId = json['from_user_id']?.toString();
    toUserId = json['to_user_id']?.toString();
    message = json['message']?.toString();
    attachment = json['attachment']?.toString();
    dateTime = json['date_time']?.toString();
    imageUrl = json['image_url']?.toString();
    tempId = json['temp_id']?.toString();
    // imageSync = json['image_sync']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['from_user_id'] = fromUserId;
    data['to_user_id'] = toUserId;
    data['message'] = message;
    data['attachment'] = attachment;
    data['date_time'] = dateTime;
    data['image_url'] = imageUrl;
    data['temp_id'] = tempId;
    // data['image_sync'] = imageSync;
    return data;
  }

  @override
  String toString() {
    return 'GetUserMessagesResponseData{id: $id, fromUserId: $fromUserId, toUserId: $toUserId, message: $message, attachment: $attachment, dateTime: $dateTime, imageUrl: $imageUrl, temp_id: $tempId}';
  }
}

class GetUserMessagesResponse {
/*
{
  "status": true,
  "data": [
    {
      "id": "1",
      "from_user_id": "3",
      "to_user_id": "4",
      "message": "test",
      "attachment": null,
      "date_time": "2023-08-08 10:15:54",
      "image_url": "uploads/speakers/3/headshot/e050c30de041aa6c97fdc35c6af270cf.jpg"
    }
  ]
}
*/

  bool? status;
  List<GetUserMessagesResponseData?>? data;

  GetUserMessagesResponse({
    this.status,
    this.data,
  });
  GetUserMessagesResponse.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <GetUserMessagesResponseData>[];
      v.forEach((v) {
        arr0.add(GetUserMessagesResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }


  @override
  String toString() {
    return 'GetUserMessagesResponse{status: $status, data: $data}';
  }
}
